### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by plh97** [Sakuyakun/Yorha-Boilerplate#3]
1.index.html文件应该放在哪哦？
问题是我的html引用的js文件有hash的，所以index.html文件只能由HtmlWebpackPlugin自动生成，然后webpack就把他生成在根目录下的dist文件里面，然后我的入口js文件的地址就错乱了。。。。。。。。。。。。。

**Comment by kobayashicoding** [comment]
@pengliheng 部署环境用了HtmlWebpackPlugin，引用的HTML模板是`src/template/index.html`这个文件，所以模板文件应该放在`src/template`目录下，带有hash的js文件会自动插入到模板文件里。根目录下的index.html是提供给生产环境的devServer用的
